class_name KitHouse
extends RefCounted
## Assembles cottages out of the Kenney Fantasy Town Kit (CC0, assets/town/).
##
## Houses are authored as *scenes* (`scenes/houses/*.tscn`, generated by
## `tools/build_house_scenes.gd`) rather than assembled at runtime, so a level
## only has to instance them. This module is the one place that knows how the
## kit's pieces fit together; the generator and any tooling share it.
##
## Kit conventions (verified against the source GLBs; 1 tile = 1 metre):
##
##   wall / wall-door / wall-window-* are *edge* pieces: at rotation 0 the panel
##   fills the +X edge of its tile. WALL_ROT maps an edge name to the rotation
##   that puts a panel on that edge, and a +90 degree turn walks
##   x+ -> z- -> x- -> z+.
##
##   roof is one slope tile whose ridge sits on one edge and rises toward the
##   other; two rows laid with their ridges facing each other make a gable. The
##   kit also ships a whole "high" family of the same pieces, which is both
##   taller and clay red, so a village can mix the two roof colours the way the
##   kit's own sample render does.
##
##   roof-gable spans a tile as a full pitch (ridge along X, eaves at Z +/-0.5)
##   and roof-gable-end closes a ridge end.

const TOWN := "res://assets/town/"

## Kit pieces are exactly one tile wide, one tile deep and one tile tall.
const TILE := 1.0
const WALL_HEIGHT := 1.0
## Rise of one roof slope tile above the wall top (the kit's own roof pitch).
const ROOF_RISE := 0.63
## Rise of a full gable tile above the wall top.
const GABLE_RISE := 0.571

## Panel edge -> Y rotation in degrees.
const WALL_ROT := {
	"x+": 0.0,
	"z-": 90.0,
	"x-": 180.0,
	"z+": 270.0,
}
## Slope ridge side -> Y rotation in degrees.
const HIGH_SIDE_ROT := {
	"x+": 0.0,
	"z-": 90.0,
	"x-": 180.0,
	"z+": 270.0,
}
## Gable ridge axis -> Y rotation in degrees.
const RIDGE_X := 0.0
## Gable-end piece: the face it closes, by rotation.
const GABLE_FACE_ROT := {
	"x+": 0.0,
	"z-": 90.0,
	"x-": 180.0,
	"z+": 270.0,
}

const SIDES: Array[String] = ["x+", "x-", "z+", "z-"]

## The kit ships two roof families. "clay" is the taller, red "high" family.
const ROOF_FAMILIES := {
	"teal": {},
	"clay": {
		"roof": "roof-high",
		"roof-gable": "roof-high-gable",
		"roof-gable-end": "roof-high-gable-end",
		"roof-flat": "roof-high-flat",
		"roof-corner": "roof-high-corner",
	},
}

## Multiplied over the kit's own colours. Slightly warm and slightly held back
## so the village sits inside the muted campaign palette without losing the
## kit's plaster / timber / tile look (SPEC 11.1).
const WALL_TINT := Color(1.10, 1.05, 0.92)
const ROOF_TINT := Color(0.88, 0.86, 0.86)

## Pieces carry their role in this metadata key, and the finished building
## carries the per-role tints under META_TINTS, so the house runtime can build
## each mesh's material (see VoxelHouse.attach_model).
const META_ROLE := "kit_role"
const META_TINTS := "kit_tints"
const ROLE_TINTS := {
	"wall": WALL_TINT,
	"trim": WALL_TINT,
	"roof": ROOF_TINT,
	"chimney": Color(0.72, 0.68, 0.62),
}

static var _scene_cache: Dictionary = {}


# ---------- Asset access ----------
static func scene(piece_name: String) -> PackedScene:
	var path := TOWN + piece_name + ".glb"
	if not _scene_cache.has(path):
		_scene_cache[path] = load(path) if ResourceLoader.exists(path) else null
	return _scene_cache[path]


static func has_piece(piece_name: String) -> bool:
	return scene(piece_name) != null


## Places one kit piece and tags it with the *role* it plays in the building
## ("wall", "roof", "trim"). Materials are deliberately left as the kit's shared
## originals: a scene that stores per-instance materials has to store copies of
## the meshes too, and a house is much better off building its own materials at
## runtime from these roles (see VoxelHouse.attach_model). That is what lets one
## cottage scorch, wet and glow without touching its neighbours.
static func place(parent: Node3D, piece_name: String, pos: Vector3, opts: Dictionary = {}) -> Node3D:
	var sc := scene(piece_name)
	if sc == null:
		push_warning("KitHouse: missing piece '%s'" % piece_name)
		return null
	var node: Node3D = sc.instantiate()
	node.name = piece_name
	node.position = pos
	node.rotation.y = deg_to_rad(float(opts.get("rot_deg", 0.0)))
	if opts.has("scale"):
		node.scale = Vector3.ONE * float(opts["scale"])
	node.set_meta(META_ROLE, str(opts.get("role", "wall")))
	parent.add_child(node)
	return node


## Every mesh under a node, the node itself included: some kit models are a bare
## MeshInstance3D.
static func mesh_instances(node: Node) -> Array[MeshInstance3D]:
	var out: Array[MeshInstance3D] = []
	if node is MeshInstance3D:
		out.append(node as MeshInstance3D)
	for c in node.get_children():
		out.append_array(mesh_instances(c))
	return out


# ---------- Buildings ----------
## World centre of tile (i, j) inside a w x d footprint whose local origin is
## the footprint's -X/-Z corner.
static func tile_center(i: int, j: int) -> Vector3:
	return Vector3((float(i) + 0.5) * TILE, 0.0, (float(j) + 0.5) * TILE)


## Tile positions along one side of a w x d footprint, -X/-Z end first.
static func side_tiles(side: String, w: int, d: int) -> Array[Vector3]:
	var out: Array[Vector3] = []
	match side:
		"x+":
			for j in d:
				out.append(tile_center(w - 1, j))
		"x-":
			for j in d:
				out.append(tile_center(0, j))
		"z+":
			for i in w:
				out.append(tile_center(i, d - 1))
		_:
			for i in w:
				out.append(tile_center(i, 0))
	return out


## Footprint of a cottage spec, in metres.
static func cottage_size(spec: Dictionary) -> Vector3:
	var w: int = maxi(2, int(spec.get("w", 3)))
	var d: int = maxi(2, int(spec.get("d", 2)))
	var height := WALL_HEIGHT + ROOF_RISE
	if bool(spec.get("chimney", true)):
		height += ROOF_RISE * 0.6
	return Vector3(float(w) * TILE, height, float(d) * TILE)


## Builds a cottage. `spec` keys:
##   "w" (int, tiles across X, default 3), "d" (int, tiles across Z, default 2)
##   "wall" ("wall" | "wall-wood", default "wall-wood")
##   "door" (side with the front door, default "z+")
##   "windows" (int, default 2)
##   "roof_style" ("teal" | "clay", default "teal")
##   "chimney" (bool, default true), "seed" (int)
##
## The returned node's origin is the footprint's -X/-Z corner at ground level.
## Its "tint_mats" metadata carries the materials runtime feedback drives.
static func build_cottage(spec: Dictionary = {}) -> Node3D:
	var root := Node3D.new()
	root.name = "Cottage"

	var w: int = maxi(2, int(spec.get("w", 3)))
	var d: int = maxi(2, int(spec.get("d", 2)))
	var wall: String = str(spec.get("wall", "wall-wood"))
	var door_side: String = str(spec.get("door", "z+"))
	var window_budget: int = int(spec.get("windows", 2))
	var chimney: bool = bool(spec.get("chimney", true))
	var family: Dictionary = ROOF_FAMILIES.get(str(spec.get("roof_style", "teal")), {})

	var wood := wall.begins_with("wall-wood")
	var door_piece := "wall-wood-door" if wood else "wall-door"
	var window_pieces: Array[String] = ["wall-window-small", "wall-window-shutters"]
	if wood:
		window_pieces = ["wall-wood-window-small"]

	var rng := RandomNumberGenerator.new()
	rng.seed = int(spec.get("seed", 0))

	var sides: Dictionary = {}
	for side in SIDES:
		sides[side] = side_tiles(side, w, d)

	# Openings are chosen first, then panels are placed around them.
	var openings: Dictionary = {}
	for side in SIDES:
		openings[side] = {}

	# Door: the middle panel of its side reads as a front door.
	var door_tiles: Array[Vector3] = sides[door_side]
	if not door_tiles.is_empty():
		openings[door_side][int(door_tiles.size() / 2)] = door_piece

	# Windows walk the sides from a seed-chosen offset so repeated cottages do
	# not all wear their windows on the same wall.
	var start := rng.randi() % SIDES.size()
	for step in SIDES.size():
		if window_budget <= 0:
			break
		var side: String = SIDES[(start + step) % SIDES.size()]
		var tiles: Array[Vector3] = sides[side]
		for idx in tiles.size():
			if window_budget <= 0:
				break
			if openings[side].has(idx):
				continue
			if rng.randf() < 0.7:
				openings[side][idx] = window_pieces[rng.randi() % window_pieces.size()]
				window_budget -= 1

	var tints := {
		"wall": spec.get("wall_tint", WALL_TINT),
		"trim": spec.get("wall_tint", WALL_TINT),
		"roof": spec.get("roof_tint", ROOF_TINT),
		"chimney": Color(0.72, 0.68, 0.62),
	}
	root.set_meta(META_TINTS, tints)

	for side in SIDES:
		var tiles: Array[Vector3] = sides[side]
		var rot: float = WALL_ROT[side]
		for idx in tiles.size():
			var piece: String = str(openings[side].get(idx, wall))
			# Wall pieces carry their own base at the local origin, so a panel
			# simply sits on the footprint's ground plane.
			place(root, piece, tiles[idx], {"rot_deg": rot, "role": "wall"})

	# Timber posts at the corners: the kit's framed look, and they hide the seam
	# where two wall panels meet.
	for cx in [0, w - 1]:
		for cz in [0, d - 1]:
			place(root, "pillar-wood", tile_center(cx, cz), {"rot_deg": 0.0, "role": "trim"})

	# --- Roof ---
	var slope_piece := str(family.get("roof", "roof"))
	for i in w:
		if d == 2:
			# Ridge runs along X at the shared edge between the two rows.
			_roof_row(root, tile_center(i, 0), HIGH_SIDE_ROT["z+"], slope_piece)
			_roof_row(root, tile_center(i, 1), HIGH_SIDE_ROT["z-"], slope_piece)
		else:
			_roof_row(root, tile_center(i, 0), RIDGE_X, str(family.get("roof-gable", "roof-gable")))

	# Gable ends close the triangle under the ridge at both ends of the run.
	if d == 2:
		for i in [0, w - 1]:
			var face := "x-" if i == 0 else "x+"
			var end_pos := Vector3((float(i) + 0.5) * TILE, WALL_HEIGHT, TILE)
			place(root, str(family.get("roof-gable-end", "roof-gable-end")), end_pos,
				{"rot_deg": GABLE_FACE_ROT[face], "role": "roof"})

	# --- Chimney, offset from the ridge so it reads against the sky. The kit's
	# chimney pieces are a tile tall each; only the top one clears the ridge. ---
	if chimney:
		var cx2 := 0 if w <= 2 else w - 1
		var anchor := tile_center(cx2, 0)
		var foot := Vector3(anchor.x - 0.30, WALL_HEIGHT + ROOF_RISE * 0.55, anchor.z + TILE * 0.85)
		place(root, "chimney-base", foot, {"role": "chimney"})
		place(root, "chimney-top", foot + Vector3(0.0, ROOF_RISE * 0.95, 0.0), {"role": "chimney"})

	return root


static func _roof_row(root: Node3D, tile_pos: Vector3, rot_deg: float, piece: String) -> void:
	place(root, piece, tile_pos + Vector3(0.0, WALL_HEIGHT, 0.0), {"rot_deg": rot_deg, "role": "roof"})
